learning_templates/basic_app/urls.py
from django.urls import path
from basic_app.views import my_other,my_relative_url

app_name = 'basic_app'

urlpatterns = [path("other/",my_other,name = "other_page_name"),
                path("relurl/",my_relative_url,name = 'relurl_page'),]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app.views import my_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',my_index,name = 'index'),
    path('usr_app/',include('usr_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def my_index(request):
    my_context_dict = {'django':" i am a one in 10000 nigger ",'killed':'04/14/1865'}
    return render(request,"basic_app/index.html",my_context_dict)

def my_other(request):
    return render(request,"basic_app/other.html")

def my_relative_url(request):
    return render(request,"basic_app/relative_url_template.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="{% url "index" %}">Home</a>
      <ul class="navbar-nav">
   <li class="nav-item active">
     <a class="nav-link" href="{% url "index" %}">Index</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url "basic_app:other_page_name" %}">Other</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url "basic_app:relurl_page" %}">Relative URL</a>
   </li>
   <li class="nav-item">
     <a class="nav-link disabled" href="{% url "admin:index" %}">Admin</a>
   </li>
 </ul>
</nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block%}
<h1>This is home!</h1>
<h2>Killing white people for money? What's not to like? - Django FreeMan</h2>
<br>
<h1>{{ django | cut:"am" }}
{{ killed | date }}
</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>This is a other Page!</h1>
<h2>I couldn't Resist - Dr.Schultz</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>This is Relative URL Page</h1>
<h2>well I can't imagine two weeks in Boston. - Calvin Candy</h2>
{% endblock %}