levelfive/levelfive/urls.py
from django.contrib import admin
from django.urls import path,include
from usr_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = 'home'),
    path('register/',include("usr_app.urls")),
    path('logout/',views.usr_logout,name = 'logout'),
    path('special/',views.special,name = "special"),
]

levelfive/usr_app/urls.py
from django.urls import path
from usr_app import views

app_name = 'usr_app'

urlpatterns = [path("register/",views.register,name = 'register'),
               path("login/",views.usr_login,name = "login"),
                ]

levelfive/usr_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):  # create a model user with additional fields like profile pic etc
    usr = models.OneToOneField(User,on_delete = User) # one to one mapping for re-use django's User Model
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = "Profile Pictures/",blank  = True)

    def __str__(self):
        return self.usr.username

levelfive/usr_app/forms.py
from django import forms
from django.contrib.auth.models import User
from usr_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput()) #password input for userform
    class Meta():# takes a model and a field
        model = User
        fields = ('username','email','password') # take only 3 fields from user

class UserFieldInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo # use our own model that has fields from User
        fields = ('portfolio_site','profile_pic') # consider the additional fields for the form

levelfive/usr_app/views.py
from django.shortcuts import render
from usr_app.forms import UserFieldInfoForm,UserForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request,"usr_app/index.html")

def usr_login(request):
    if request.method == "POST":
        usr_name = request.POST.get('usrname')
        password = request.POST.get('pwd')
        user = authenticate(username = usr_name,password = password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponseRedirect("Error: Account not Active!")
        else:
            print("Someone tried to login and failed")
            print("Username: {} Password: {}".format(usr_name,password))
            return HttpResponseRedirect("Login Failed!")
    else:
        return render(request,"usr_app/login.html",{})

@login_required
def usr_logout(request):
    logout(request)
    return render(request,"usr_app/logout.html",{})

@login_required
def special(request):
    return render(request,"usr_app/special.html",{})

def register(request):
    registered = False
    if request.method == "POST": # if submitted
        user_form = UserForm(data = request.POST) # get username,email,password
        profile_form = UserFieldInfoForm(data = request.POST) # get url,profile pic

        if user_form.is_valid() and profile_form.is_valid():

            usr_db = user_form.save() #save the form in db
            usr_db.set_password(usr_db.password)#hash password
            usr_db.save()#save password in db

            profile_db = profile_form.save(commit = False) # save after making changes
            profile_db.usr = usr_db # link user form and profile form

            if 'profile_pic' in request.FILES: # if http had picture
                profiledb.profile_pic = request.Files['profile_pic'] # make it ready to store it in db

            profile_db.save()# save in db

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm() # Refreshed or first time visit
        profile_form = UserFieldInfoForm()

    return render(request,"usr_app/Registration.html",{'user_form':user_form,'user_profile_form':profile_form,"registered":registered})

levelfive/templates/usr_app/Registration.html
{% extends 'usr_app/base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class="Container">
  {% if registered %}
  <h1 class = "display-4" >Thankyou for Registering!</h1>
  {% else %}
    <h1 class = "display-4"> Welcome to register page</h1>
    <br>
  <h1 class = "display-4" >Register Here</h1>
  <h3 class = "display-4" >Fill out the form!</h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{user_form.as_p}}
    {{user_profile_form.as_p}}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}
  </div>
{% endblock %}

levelfive/templates/usr_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
   <li class="nav-item active">
     <a class="nav-link" href="{% url "home" %}">Home</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url "usr_app:register" %}">Register</a>
   </li>
   {% if user.is_authenticated %}
    Hello, {{user.username}}
   <li>
     <a class = "nav-link" href="{% url "logout" %}?next=/logout">Logout</a>
   </li>
   <li>
     <a class = "nav-link" href="{% url "special" %}">Special</a>
   </li>
   {% else %}
   <li>
     <a class = "nav-link" href="{% url "usr_app:login" %}">Login</a>
   </li>
   {% endif %}

 </ul>
    </nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
    </div>
  </body>
</html>

levelfive/templates/usr_app/index.html
{% extends 'usr_app/base.html' %}

{% block body_block %}

<div class="container">
         <h1 class="display-4">Welcome to the Home page!</h1>
  </div>
</div>
{% endblock %}

levelfive/templates/usr_app/login.html
{% extends 'usr_app/base.html' %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Login page</h1>
    <form action="{% url "usr_app:login" %}" method="post">
      {% csrf_token %}
      <label for="usrname">Username: </label>
      <input type="text" name="usrname" placeholder="Enter email or Username ">
      <label for="pwd">Password: </label>
      <input type="password" name="pwd" >
      <input type="submit" value="Login">
    </form>
  </div>
{% endblock %}

levelfive/templates/usr_app/logout.html
{% extends "usr_app/base.html"  %}
{% block body_block %}
{% csrf_token %}
<h1 class = "display-4" >Thankyou for your time with us!</h1>
{% endblock %}

levelfive/templates/usr_app/special.html
{% extends "usr_app/base.html" %}

{% block body_block %}
    <p>You are viewing this only because you are logged in</p>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  {% endblock %}